"""Add execution log duration metrics

Revision ID: 1be58d82328b
Revises: 1f5cad08f1dd
Create Date: 2026-06-10 23:17:54.815629

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1be58d82328b'
down_revision: Union[str, Sequence[str], None] = '1f5cad08f1dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('execution_logs', sa.Column('start_time', sa.DateTime(), nullable=True))
    op.add_column('execution_logs', sa.Column('end_time', sa.DateTime(), nullable=True))
    op.add_column('execution_logs', sa.Column('duration_ms', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('execution_logs', 'duration_ms')
    op.drop_column('execution_logs', 'end_time')
    op.drop_column('execution_logs', 'start_time')
    # ### end Alembic commands ###
